image: ghcr.io/leapkh/android-ci:1.0.1

stages:
  - build

build_apk:
  stage: build
  only:
    - /^(uat|prd)-\d(\.\d{1}){2}/
  script:
    - ./gradlew assembleUatRelease
    - apkDir="app/build/outputs/apk/uat/release"
    - apkMetaFile="$apkDir/output-metadata.json"
    - apkFile=$(cat $apiMetaFile | jq -r '.elements[0].outputFile')
    - cp "$apiDir/$apkFile" "visit-me.apk"
    - echo "Done"
  artifacts:
    paths:
      - visit-me.apk